
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     browser/browsing_data/browsing_data_remover.h

package org.chromium.chrome.browser;

public class TimePeriod {
  public static final int LAST_HOUR = 0;
  public static final int LAST_DAY = 1;
  public static final int LAST_WEEK = 2;
  public static final int FOUR_WEEKS = 3;
  public static final int EVERYTHING = 4;
  public static final int TIME_PERIOD_LAST = 4;
}
