
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     offline_pages/offline_page_feature.h

package org.chromium.components.offlinepages;

public class FeatureMode {
  public static final int DISABLED = 0;
  public static final int ENABLED_AS_BOOKMARKS = 1;
  public static final int ENABLED_AS_SAVED_PAGES = 2;
}
