
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     security_state/security_state_model.h

package org.chromium.components.security_state;

public class ConnectionSecurityLevel {
  public static final int NONE = 0;
  public static final int EV_SECURE = 1;
  public static final int SECURE = 2;
  public static final int SECURITY_WARNING = 3;
  public static final int SECURITY_POLICY_WARNING = 4;
  public static final int SECURITY_ERROR = 5;
}
