
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../components/signin/core/browser/signin_metrics.h

package org.chromium.chrome.browser.signin;

public class SigninReason {
  public static final int SIGNIN_PRIMARY_ACCOUNT = 0;
  public static final int ADD_SECONDARY_ACCOUNT = 1;
  public static final int REAUTHENTICATION = 2;
  public static final int UNLOCK = 3;
  public static final int UNKNOWN_REASON = 4;
  public static final int MAX = 5;
}
