
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     omnibox/browser/autocomplete_match.h

package org.chromium.chrome.browser.omnibox;

public class MatchClassificationStyle {
  public static final int NONE = 0;
  public static final int URL = 1 << 0;
  public static final int MATCH = 1 << 1;
  public static final int DIM = 1 << 2;
}
