
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     signin/core/browser/signin_investigator.h

package org.chromium.signin;

public class InvestigatedScenario {
  public static final int UPGRADE_LOW_RISK = 0;
  public static final int UPGRADE_HIGH_RISK = 1;
  public static final int SAME_ACCOUNT = 2;
  public static final int DIFFERENT_ACCOUNT = 3;
  public static final int HISTOGRAM_COUNT = 4;
}
